server:
  port: 9999

spring:
  application:
    name: products-ms
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/compasso_db?allowPublicKeyRetrival=true&sslMode=DISABLED
    username: root
    password: bicicleta123

